In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
trash_df = pd.read_csv('../data/trash_hauler_report.csv')
trash_df.head()

,Request Number,Date Opened,Request,Description,Incident Address,Zip Code,Trash Hauler,Trash Route,Council District,State Plan X,State Plan Y
0,25270,11/1/2017,Trash - Backdoor,"house with the wheel chair ramp, they share dr...",3817 Crouch Dr,37207.0,RED RIVER,3205,2.0,1727970.412,686779.4781
1,25274,11/1/2017,Trash - Curbside/Alley Missed Pickup,Curb/Trash miss Tuesday.,4028 Clarksville Pike,37218.0,RED RIVER,4202,1.0,1721259.366,685444.7996
2,25276,11/1/2017,Trash - Curbside/Alley Missed Pickup,Curb/trash miss Tuesday.,6528 Thunderbird Dr,37209.0,RED RIVER,4205,20.0,1707026.753,659887.4716
3,25307,11/1/2017,Trash - Curbside/Alley Missed Pickup,missed,2603 old matthews rd,37207.0,WASTE IND,2206,2.0,1735691.771,685027.2459
4,25312,11/1/2017,Trash - Curbside/Alley Missed Pickup,Missed the even side of the road.,604 croley dr,37209.0,RED RIVER,4203,20.0,1710185.772,664205.1011

In [3]:
trash_df.shape

(20226, 11)

In [4]:
trash_df['Request '].value_counts()

Request
Trash - Curbside/Alley Missed Pickup    15028
Trash - Backdoor                         2629
Trash Collection Complaint               2312
Damage to Property                        257
Name: count, dtype: int64

In [5]:
trash_df = trash_df.rename(columns = {'Request ': 'Request'})
trash_df.columns

Index(['Request Number', 'Date Opened', 'Request', 'Description',
       'Incident Address', 'Zip Code', 'Trash Hauler', 'Trash Route',
       'Council District', 'State Plan X', 'State Plan Y'],
      dtype='object')

In [6]:
trash_df['Request'].value_counts()

Request
Trash - Curbside/Alley Missed Pickup    15028
Trash - Backdoor                         2629
Trash Collection Complaint               2312
Damage to Property                        257
Name: count, dtype: int64

In [7]:
request_count = trash_df['Request'].value_counts()
request_count = request_count.reset_index()
request_count

                                Request  count
0  Trash - Curbside/Alley Missed Pickup  15028
1                      Trash - Backdoor   2629
2            Trash Collection Complaint   2312
3                    Damage to Property    257

In [8]:
trash_df['Zip Code'].dtype

dtype('float64')

In [9]:
trash_df['Zip Code'].astype(float).astype(str).str.replace('.0','')

0        37207
1        37218
2        37209
3        37207
4        37209
         ...
20221    37013
20222    37206
20223    37214
20224    37013
20225    37217
Name: Zip Code, Length: 20226, dtype: object

In [10]:
trash_df['Zip Code'] = trash_df['Zip Code'].astype(float).astype(str).str.replace('.0','')
trash_df.head()

,Request Number,Date Opened,Request,Description,Incident Address,Zip Code,Trash Hauler,Trash Route,Council District,State Plan X,State Plan Y
0,25270,11/1/2017,Trash - Backdoor,"house with the wheel chair ramp, they share dr...",3817 Crouch Dr,37207,RED RIVER,3205,2.0,1727970.412,686779.4781
1,25274,11/1/2017,Trash - Curbside/Alley Missed Pickup,Curb/Trash miss Tuesday.,4028 Clarksville Pike,37218,RED RIVER,4202,1.0,1721259.366,685444.7996
2,25276,11/1/2017,Trash - Curbside/Alley Missed Pickup,Curb/trash miss Tuesday.,6528 Thunderbird Dr,37209,RED RIVER,4205,20.0,1707026.753,659887.4716
3,25307,11/1/2017,Trash - Curbside/Alley Missed Pickup,missed,2603 old matthews rd,37207,WASTE IND,2206,2.0,1735691.771,685027.2459
4,25312,11/1/2017,Trash - Curbside/Alley Missed Pickup,Missed the even side of the road.,604 croley dr,37209,RED RIVER,4203,20.0,1710185.772,664205.1011

In [11]:
trash_df['Zip Code'].value_counts()

Zip Code
37013    2278
37211    2248
37205    1491
37209    1411
37215    1404
37207    1300
37115    1266
37206    1217
37208    1039
37214    1004
37218     983
37216     841
37217     832
37204     635
37212     601
37210     550
37203     394
37220     289
37027     168
nan        75
37189      60
37221      48
37219      42
37201      35
37076       5
37138       5
37086       3
37213       1
37228       1
Name: count, dtype: int64

In [14]:
zip_count = trash_df['Zip Code'].value_counts()
zip_count = zip_count.reset_index()
zip_count

   Zip Code  count
0     37013   2278
1     37211   2248
2     37205   1491
3     37209   1411
4     37215   1404
5     37207   1300
6     37115   1266
7     37206   1217
8     37208   1039
9     37214   1004
10    37218    983
11    37216    841
12    37217    832
13    37204    635
14    37212    601
15    37210    550
16    37203    394
17    37220    289
18    37027    168
19      nan     75
20    37189     60
21    37221     48
22    37219     42
23    37201     35
24    37076      5
25    37138      5
26    37086      3
27    37213      1
28    37228      1