In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
trash_df = pd.read_csv('../data/trash_hauler_report.csv')
trash_df.head()

,Request Number,Date Opened,Request,Description,Incident Address,Zip Code,Trash Hauler,Trash Route,Council District,State Plan X,State Plan Y
0,25270,11/1/2017,Trash - Backdoor,"house with the wheel chair ramp, they share dr...",3817 Crouch Dr,37207.0,RED RIVER,3205,2.0,1727970.412,686779.4781
1,25274,11/1/2017,Trash - Curbside/Alley Missed Pickup,Curb/Trash miss Tuesday.,4028 Clarksville Pike,37218.0,RED RIVER,4202,1.0,1721259.366,685444.7996
2,25276,11/1/2017,Trash - Curbside/Alley Missed Pickup,Curb/trash miss Tuesday.,6528 Thunderbird Dr,37209.0,RED RIVER,4205,20.0,1707026.753,659887.4716
3,25307,11/1/2017,Trash - Curbside/Alley Missed Pickup,missed,2603 old matthews rd,37207.0,WASTE IND,2206,2.0,1735691.771,685027.2459
4,25312,11/1/2017,Trash - Curbside/Alley Missed Pickup,Missed the even side of the road.,604 croley dr,37209.0,RED RIVER,4203,20.0,1710185.772,664205.1011

In [4]:
trash_df.shape

(20226, 11)

In [5]:
trash_df['Request '].value_counts()

Request
Trash - Curbside/Alley Missed Pickup    15028
Trash - Backdoor                         2629
Trash Collection Complaint               2312
Damage to Property                        257
Name: count, dtype: int64

In [6]:
trash_df = trash_df.rename(columns = {'Request ': 'Request'})
trash_df.columns

Index(['Request Number', 'Date Opened', 'Request', 'Description',
       'Incident Address', 'Zip Code', 'Trash Hauler', 'Trash Route',
       'Council District', 'State Plan X', 'State Plan Y'],
      dtype='object')

In [7]:
trash_df['Request'].value_counts()

Request
Trash - Curbside/Alley Missed Pickup    15028
Trash - Backdoor                         2629
Trash Collection Complaint               2312
Damage to Property                        257
Name: count, dtype: int64

In [8]:
request_count = trash_df['Request'].value_counts()
request_count = request_count.reset_index()
request_count

                                Request  count
0  Trash - Curbside/Alley Missed Pickup  15028
1                      Trash - Backdoor   2629
2            Trash Collection Complaint   2312
3                    Damage to Property    257

In [9]:
trash_df['Zip Code'].dtype

dtype('float64')

In [10]:
trash_df['Zip Code'].astype(float).astype(str).str.replace('.0','')

0        37207
1        37218
2        37209
3        37207
4        37209
         ...
20221    37013
20222    37206
20223    37214
20224    37013
20225    37217
Name: Zip Code, Length: 20226, dtype: object

In [11]:
trash_df['Zip Code'] = trash_df['Zip Code'].astype(float).astype(str).str.replace('.0','')
trash_df.head()

,Request Number,Date Opened,Request,Description,Incident Address,Zip Code,Trash Hauler,Trash Route,Council District,State Plan X,State Plan Y
0,25270,11/1/2017,Trash - Backdoor,"house with the wheel chair ramp, they share dr...",3817 Crouch Dr,37207,RED RIVER,3205,2.0,1727970.412,686779.4781
1,25274,11/1/2017,Trash - Curbside/Alley Missed Pickup,Curb/Trash miss Tuesday.,4028 Clarksville Pike,37218,RED RIVER,4202,1.0,1721259.366,685444.7996
2,25276,11/1/2017,Trash - Curbside/Alley Missed Pickup,Curb/trash miss Tuesday.,6528 Thunderbird Dr,37209,RED RIVER,4205,20.0,1707026.753,659887.4716
3,25307,11/1/2017,Trash - Curbside/Alley Missed Pickup,missed,2603 old matthews rd,37207,WASTE IND,2206,2.0,1735691.771,685027.2459
4,25312,11/1/2017,Trash - Curbside/Alley Missed Pickup,Missed the even side of the road.,604 croley dr,37209,RED RIVER,4203,20.0,1710185.772,664205.1011

In [12]:
trash_df['Zip Code'].value_counts().head()

Zip Code
37013    2278
37211    2248
37205    1491
37209    1411
37215    1404
Name: count, dtype: int64

In [13]:
zip_count = trash_df['Zip Code'].value_counts()
zip_count = zip_count.reset_index()
zip_count.head()

  Zip Code  count
0    37013   2278
1    37211   2248
2    37205   1491
3    37209   1411
4    37215   1404

In [19]:
trash_df['Incident Address'] = trash_df['Incident Address'].str.title()
trash_df.head()

,Request Number,Date Opened,Request,Description,Incident Address,Zip Code,Trash Hauler,Trash Route,Council District,State Plan X,State Plan Y
0,25270,11/1/2017,Trash - Backdoor,"house with the wheel chair ramp, they share dr...",3817 Crouch Dr,37207,RED RIVER,3205,2.0,1727970.412,686779.4781
1,25274,11/1/2017,Trash - Curbside/Alley Missed Pickup,Curb/Trash miss Tuesday.,4028 Clarksville Pike,37218,RED RIVER,4202,1.0,1721259.366,685444.7996
2,25276,11/1/2017,Trash - Curbside/Alley Missed Pickup,Curb/trash miss Tuesday.,6528 Thunderbird Dr,37209,RED RIVER,4205,20.0,1707026.753,659887.4716
3,25307,11/1/2017,Trash - Curbside/Alley Missed Pickup,missed,2603 Old Matthews Rd,37207,WASTE IND,2206,2.0,1735691.771,685027.2459
4,25312,11/1/2017,Trash - Curbside/Alley Missed Pickup,Missed the even side of the road.,604 Croley Dr,37209,RED RIVER,4203,20.0,1710185.772,664205.1011

In [28]:
trash_df['Address2'] = trash_df['Incident Address'].str.split(',', expand = True)[0]

In [29]:
trash_df['City'] = trash_df['Incident Address'].str.split(',', expand = True)[1]
trash_df.head()

,Request Number,Date Opened,Request,Description,Incident Address,Zip Code,Trash Hauler,Trash Route,Council District,State Plan X,State Plan Y,City,Address2
0,25270,11/1/2017,Trash - Backdoor,"house with the wheel chair ramp, they share dr...",3817 Crouch Dr,37207,RED RIVER,3205,2.0,1727970.412,686779.4781,None,3817 Crouch Dr
1,25274,11/1/2017,Trash - Curbside/Alley Missed Pickup,Curb/Trash miss Tuesday.,4028 Clarksville Pike,37218,RED RIVER,4202,1.0,1721259.366,685444.7996,None,4028 Clarksville Pike
2,25276,11/1/2017,Trash - Curbside/Alley Missed Pickup,Curb/trash miss Tuesday.,6528 Thunderbird Dr,37209,RED RIVER,4205,20.0,1707026.753,659887.4716,None,6528 Thunderbird Dr
3,25307,11/1/2017,Trash - Curbside/Alley Missed Pickup,missed,2603 Old Matthews Rd,37207,WASTE IND,2206,2.0,1735691.771,685027.2459,None,2603 Old Matthews Rd
4,25312,11/1/2017,Trash - Curbside/Alley Missed Pickup,Missed the even side of the road.,604 Croley Dr,37209,RED RIVER,4203,20.0,1710185.772,664205.1011,None,604 Croley Dr

In [33]:
address_count = trash_df['Incident Address'].value_counts()
address_count = address_count.reset_index()
address_count.head()

                                    Incident Address  count
0                                  3710 N Natchez Ct     21
1                           5135 Hickory Hollow Pkwy     21
2  6007 Obrien Ave, Nashville, Tn 37209, United S...     19
3  12546 Old Hickory Blvd, Nashville, Tn 37013, U...     19
4  802 Crescent Rd, Nashville, Tn 37205, United S...     18

In [35]:
address2_count = trash_df['Address2'].value_counts()
address2_count = address2_count.reset_index()
address2_count.head()

                   Address2  count
0   110 George L Davis Blvd     29
1  5135 Hickory Hollow Pkwy     23
2         3710 N Natchez Ct     22
3    12546 Old Hickory Blvd     21
4           6007 Obrien Ave     20

In [42]:
#this didnt work
missed_text = ['missed', 'miss', 'skip', 'skipped', 'not picked', 'failed', 'fail', 'forgot']

In [45]:
trash_df['Missed Trash'] = trash_df['Description'].str.contains('missed|miss|skip|skipped|not picked|failed|fail|forgot|never|did not', case=False, na=False)
trash_df.head()

,Request Number,Date Opened,Request,Description,Incident Address,Zip Code,Trash Hauler,Trash Route,Council District,State Plan X,State Plan Y,City,Address2,Missed Trash
0,25270,11/1/2017,Trash - Backdoor,"house with the wheel chair ramp, they share dr...",3817 Crouch Dr,37207,RED RIVER,3205,2.0,1727970.412,686779.4781,None,3817 Crouch Dr,False
1,25274,11/1/2017,Trash - Curbside/Alley Missed Pickup,Curb/Trash miss Tuesday.,4028 Clarksville Pike,37218,RED RIVER,4202,1.0,1721259.366,685444.7996,None,4028 Clarksville Pike,True
2,25276,11/1/2017,Trash - Curbside/Alley Missed Pickup,Curb/trash miss Tuesday.,6528 Thunderbird Dr,37209,RED RIVER,4205,20.0,1707026.753,659887.4716,None,6528 Thunderbird Dr,True
3,25307,11/1/2017,Trash - Curbside/Alley Missed Pickup,missed,2603 Old Matthews Rd,37207,WASTE IND,2206,2.0,1735691.771,685027.2459,None,2603 Old Matthews Rd,True
4,25312,11/1/2017,Trash - Curbside/Alley Missed Pickup,Missed the even side of the road.,604 Croley Dr,37209,RED RIVER,4203,20.0,1710185.772,664205.1011,None,604 Croley Dr,True

In [83]:
trash_df['Missed2'] = (trash_df['Description'].str.contains('missed|miss|skip|skipped|not picked|failed|fail|forgot|never|did not', case=False, na=False)
    | (trash_df['Request'] == 'Trash - Curbside/Alley Missed Pickup'))
trash_df.head()

,Request Number,Date Opened,Request,Description,Incident Address,Zip Code,Trash Hauler,Trash Route,Council District,State Plan X,State Plan Y,City,Address2,Missed Trash,Address3,Missed2
0,25270,11/1/2017,Trash - Backdoor,"house with the wheel chair ramp, they share dr...",3817 Crouch Dr,37207,RED RIVER,3205,2.0,1727970.412,686779.4781,None,3817 Crouch Dr,False,3817 Crouch Dr 37207,False
1,25274,11/1/2017,Trash - Curbside/Alley Missed Pickup,Curb/Trash miss Tuesday.,4028 Clarksville Pike,37218,RED RIVER,4202,1.0,1721259.366,685444.7996,None,4028 Clarksville Pike,True,4028 Clarksville Pike 37218,True
2,25276,11/1/2017,Trash - Curbside/Alley Missed Pickup,Curb/trash miss Tuesday.,6528 Thunderbird Dr,37209,RED RIVER,4205,20.0,1707026.753,659887.4716,None,6528 Thunderbird Dr,True,6528 Thunderbird Dr 37209,True
3,25307,11/1/2017,Trash - Curbside/Alley Missed Pickup,missed,2603 Old Matthews Rd,37207,WASTE IND,2206,2.0,1735691.771,685027.2459,None,2603 Old Matthews Rd,True,2603 Old Matthews Rd 37207,True
4,25312,11/1/2017,Trash - Curbside/Alley Missed Pickup,Missed the even side of the road.,604 Croley Dr,37209,RED RIVER,4203,20.0,1710185.772,664205.1011,None,604 Croley Dr,True,604 Croley Dr 37209,True

In [46]:
trash_df['Missed Trash'].value_counts()

Missed Trash
True     14547
False     5679
Name: count, dtype: int64

In [51]:
trash_df['Trash Hauler'] = trash_df['Trash Hauler'].replace('Metro', 'METRO')

In [63]:
hauler_count = trash_df['Missed Trash'].groupby(trash_df['Trash Hauler']).value_counts()
hauler_count = hauler_count.reset_index()
hauler_count.head()

  Trash Hauler  Missed Trash  count
0        METRO          True   2417
1        METRO         False   1163
2    RED RIVER          True  10639
3    RED RIVER         False   3756
4    WASTE IND          True    886

In [57]:
trash_df['Address3'] = trash_df['Address2'] + ' ' + trash_df['Zip Code']
trash_df.head()

,Request Number,Date Opened,Request,Description,Incident Address,Zip Code,Trash Hauler,Trash Route,Council District,State Plan X,State Plan Y,City,Address2,Missed Trash,Address3
0,25270,11/1/2017,Trash - Backdoor,"house with the wheel chair ramp, they share dr...",3817 Crouch Dr,37207,RED RIVER,3205,2.0,1727970.412,686779.4781,None,3817 Crouch Dr,False,3817 Crouch Dr 37207
1,25274,11/1/2017,Trash - Curbside/Alley Missed Pickup,Curb/Trash miss Tuesday.,4028 Clarksville Pike,37218,RED RIVER,4202,1.0,1721259.366,685444.7996,None,4028 Clarksville Pike,True,4028 Clarksville Pike 37218
2,25276,11/1/2017,Trash - Curbside/Alley Missed Pickup,Curb/trash miss Tuesday.,6528 Thunderbird Dr,37209,RED RIVER,4205,20.0,1707026.753,659887.4716,None,6528 Thunderbird Dr,True,6528 Thunderbird Dr 37209
3,25307,11/1/2017,Trash - Curbside/Alley Missed Pickup,missed,2603 Old Matthews Rd,37207,WASTE IND,2206,2.0,1735691.771,685027.2459,None,2603 Old Matthews Rd,True,2603 Old Matthews Rd 37207
4,25312,11/1/2017,Trash - Curbside/Alley Missed Pickup,Missed the even side of the road.,604 Croley Dr,37209,RED RIVER,4203,20.0,1710185.772,664205.1011,None,604 Croley Dr,True,604 Croley Dr 37209

In [77]:
address3_count = trash_df['Address3'].value_counts()
address3_count = address3_count.reset_index()
address3_count.head()

                         Address3  count
0   110 George L Davis Blvd 37203     28
1  5135 Hickory Hollow Pkwy 37013     23
2         3710 N Natchez Ct 37211     22
3    12546 Old Hickory Blvd 37013     21
4           6007 Obrien Ave 37209     20

In [62]:
trash_df.loc[trash_df["Missed Trash"] == True, "Address3"].groupby(trash_df['Trash Hauler']).count()

Trash Hauler
METRO         2416
RED RIVER    10639
WASTE IND      886
Name: Address3, dtype: int64

In [71]:
not_missed_desc = trash_df.loc[trash_df['Missed Trash'] == False]['Description']
not_missed_desc = not_missed_desc.reset_index()
not_missed_desc

      index                                        Description
0         0  house with the wheel chair ramp, they share dr...
1         5  left trash cart in middle of driveway instead ...
2         6  Trash/emptied Wednesday & now metal black-mail...
3        16       trash carts all tossed in road after pick up
4        20  A resident is complaining that a trash truck r...
...     ...                                                ...
5674  20208  Three months of inconsistent trash pickup some...
5675  20211  MANAGER SAYS HE WITNESSED THE TRASH TRUCK COME...
5676  20215  trash truck broke a limb out of her tree and l...
5677  20218                         Friday/paid backdoor trash
5678  20222                                       entire alley

[5679 rows x 2 columns]